### ISSUE TITLE
[Feature] 프로젝트 초기세팅+배포 CI/CD세팅

### ISSUE THREAD

**Issue by nicerjs23** [TEAM-LifeTail/2024-sharedog-frontend#1]
## ✔️ Issue

프로젝트 초기세팅과 배포를 위한 세팅 

## 📝 To-do

- [x] 프로젝트 폴더구조 정리 
- [x] 모바일뷰 레이아웃 설정 
- [x] 메인페이지 라우터 연결 
- [x]  vercel을 통한 배포 설정하기 
- [x]  html OG 이미지 설명넣기 -favicon은 추후 추가 

## 🛠 Working time

1D

**Comment by nicerjs23** [comment]
다했어요!!

**Comment by nicerjs23** [comment]
test
