### ISSUE TITLE
[Feature] 홈화면,공통푸터 구현 

### ISSUE THREAD

**Issue by nicerjs23** [TEAM-LifeTail/2024-sharedog-frontend#21]
## ✔️ Issue

홈화면과 공통푸터 구현합니다 
| <img src="https://github.com/user-attachments/assets/d04cca7f-6a2c-4aaf-b228-59a735d4d682" style="width: 300px; height: auto;"> | <img src="https://github.com/user-attachments/assets/b83b73ae-b92b-4b74-a405-0b50879cdee0" style="width: 100px; height: auto;"> |
|-----------------------------------------------------------|-----------------------------------------------------------|

## 📝 To-do

- [x] 공통푸터 구현 (common컴포넌트에 넣기)
- [x] 홈화면 구현 
- [ ] 홈화면 로그인안했을때 모달구현/터치 비활성화 
- [ ] 홈화면 테스트 진행 후 슬라이드 순서변경 
- [ ] 더미데이터 연결 -필터,게시글은 연결완료//슬라이드,프로필 연결필요  
## 🛠 Working time

~24/01/6
