### ISSUE TITLE
[Feature] 헌혈견 테스트 제작

### ISSUE THREAD

**Issue by pedro0527** [TEAM-LifeTail/2024-sharedog-frontend#4]
## ✔️ Issue

헌혈견 테스트 페이지 제작합니다

## 📝 To-do

- [ ] 헌혈견 테스트 페이지 UI 디자인 구현
- [ ] 헌혈견 테스트 페이지 버튼 구현
- [ ] 헌혈견 테스트 페이지 progress bar 구현

## 🛠 Working time

1hr 30m
